### ISSUE TITLE
autenticazione windows

### ISSUE THREAD

**Issue by zufolo441** [RegioneER/al.verificafirme#2]
Il programma non prevede un' autenticazione basata sull' utente corrente del client. 
username = string.Format(@"{0}\{1}", httpRequest.Headers["Domain"], httpRequest.Headers["Username"]);
restituisce una stringa vuota.

**Comment by AlApplicazioni** [comment]
Buongiorno, mi scuso per il ritardo nella risposta, ma mi era sfuggita la richiesta.

L’applicativo non prevede la gestione dell’autenticazione, ma solo della profilazione. Quindi la parte di autenticazione deve essere sviluppata in base al propria infrastruttura. 

Questa modalità è stata voluta per non gestire un sistema di autenticazione all’interno dell’applicativo, perché ogni ente hai il suo sistema di autenticazione.

Per esempio, nel caso della Regione Emilia-Romagna, quando tramite Identity Manager un utente viene abilitato all’applicativo, uno script va ad inserire in automatico le sue credenziali nel database nelle tabelle Utente e UtenteProfilo con un profilo di default.
Almeno un utente deve avere il profilo Amministratore.

Rimango a disposizione per eventuali chiarimenti.

**Comment by zufolo441** [comment]
Grazie per la risposta. i miei colleghi incaricheranno il produttore di implementare un' autenticazione specifica per la nostra infrastruttura di rete.
